### ISSUE TITLE
no printing

### ISSUE THREAD

**Issue by faridhwisanggeni** [jadefox10200/goprint#3]
having try this code, but only success on the spool, status on the printer board is 'printing' but not really printing.. then dissappear :)

**Comment by jadefox10200** [comment]
> having try this code, but only success on the spool, status on the printer board is 'printing' but not really printing.. then dissappear :)

What printer are you using and what type of file are you sending to print?

**Comment by jadefox10200** [comment]
I'm assuming this was because of the datatype but being closed due to no response and no details provided.

**Comment by TCutullic** [comment]
Hello, i have the same problem. i send a .pdf to the printer HP Color LaserJet M652 and the document's status is "printing" and never printed. But it does not disappear except when i cancel the task.
