### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by icobani** [jadefox10200/goprint#4]
Hi,

I m trying to install but i get this error during installation.

```
C:\Users\Lenovo\go\src\wsClient>go get github.com/jadefox10200/goprint
# github.com/jadefox10200/goprint
..\github.com\jadefox10200\goprint\main.go:602:20: undefined: createDCProc
..\github.com\jadefox10200\goprint\main.go:610:20: undefined: resetDCProc
..\github.com\jadefox10200\goprint\main.go:618:20: undefined: deleteDCProc
..\github.com\jadefox10200\goprint\main.go:628:18: undefined: getDeviceCapsProc
..\github.com\jadefox10200\goprint\main.go:641:20: undefined: startDocProc
..\github.com\jadefox10200\goprint\out.go:27:7: cannot use _ as value

```

**Comment by jairforero** [comment]
I have you error how fix? 
E:\Go\go\pkg\mod\github.com\jadefox10200\goprint@v0.0.0-20210306071919-81d8e344dbab\main.go:602:20: undefined: createDCProc
E:\Go\go\pkg\mod\github.com\jadefox10200\goprint@v0.0.0-20210306071919-81d8e344dbab\main.go:610:20: undefined: resetDCProc
E:\Go\go\pkg\mod\github.com\jadefox10200\goprint@v0.0.0-20210306071919-81d8e344dbab\main.go:618:20: undefined: deleteDCProc
E:\Go\go\pkg\mod\github.com\jadefox10200\goprint@v0.0.0-20210306071919-81d8e344dbab\main.go:628:18: undefined: getDeviceCapsProc
E:\Go\go\pkg\mod\github.com\jadefox10200\goprint@v0.0.0-20210306071919-81d8e344dbab\main.go:641:20: undefined: startDocProc
E:\Go\go\pkg\mod\github.com\jadefox10200\goprint@v0.0.0-20210306071919-81d8e344dbab\out.go:27:7: cannot use _ as value

**Comment by mec07** [comment]
I'm seeing this too...

**Comment by jadefox10200** [comment]
Ok, I have commented out the HDC processes as they are incomplete and shouldn't have been uploaded. Please file a new issue if the situations persists. Thanks.
